Vagrant.configure(2) do |config|
    # Golden ref
    # http://blog.zenika.com/index.php?post/2014/10/07/Setting-up-a-development-environment-using-Docker-and-Vagrant

	config.vm.define "db" do |a|
		a.vm.provider "docker" do |d|
			d.image = "elasticsearch"
			d.ports = ['9200:9200']
			d.vagrant_vagrantfile = "host/Vagrantfile"
			d.name = "db"
		end
	end

	config.vm.define "app" do |a|
		a.vm.provider "docker" do |d|
			d.image = "continuumio/anaconda3"
			d.ports = ['8888:8888']
			d.vagrant_vagrantfile = "host/Vagrantfile"
			d.name = 'anaconda'
			# Check: vagrant docker-run app -- ls /vagrant/anaconda/start_jupyter.sh
			d.cmd = ["/vagrant/anaconda/start_jupyter.sh"]
			d.link("db:db")
		end
	end

	config.vm.define "pylucene" do |a|
		a.vm.provider "docker" do |d|
			d.image = "coady/pylucene"
			d.vagrant_vagrantfile = "host/Vagrantfile"
			d.name = 'pylucene'
			d.link("db:db")
		end
	end

end
