

Vagrant.configure("2") do |config|
	config.vm.define "web" do |web|
		web.vm.provider "docker" do |d|
			d.build_dir = "web"
			d.name = "web"
			d.ports = ["9312:9312"]
		end
		web.vm.network "forwarded_port", guest: 9312, host: 9312
	end
	
	config.vm.define "dev", primary: true do |dev|
		dev.vm.provider "docker" do |d|
			d.build_dir = "dev"
			d.name = "dev"
			d.has_ssh = true
			d.ports = ["6800:6800"]
			d.link("web:web")
		end
		
	    dev.ssh.username = 'root'
	    dev.ssh.private_key_path = 'insecure_key'
	
		dev.vm.network "forwarded_port", guest: 6800, host: 6800
	end
end
